// <auto-generated />
namespace SpyUserControl.Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version_101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_101));
        
        string IMigrationMetadata.Id
        {
            get { return "201608181606585_version_1.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
