// <auto-generated />
namespace DevStore.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialze_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialze_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201706062334409_Initialze_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
